AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Create resources supporting the bathy extract system to subset and grid CSB and multibeam data

Parameters:
  EnvType:
    Description: Environment type
    Default: prod
    Type: String
    AllowedValues: [prod, dev, test]
    ConstraintDescription: must specify prod, dev, or test

  LambdaRole:
    Description: IAM role used by Lambdas
    Default: arn:aws:iam::282856304593:role/csb-bathy-lambda-role
    Type: String

  SnfRole:
    Description: IAM role use by Step Functions
    Default: arn:aws:iam::282856304593:role/csb-bathy-sfn-role
    Type: String

  ParquetPartitionedTable:
    Description: Parquet files partitioned using H3 level 4 indexes
    Default: csb_parquet_level4
    Type: String

  BathyOrdersTable:
    Description: Athena table of data extract requests
    Default: bathy-orders
    Type: String

  AthenaDatabase:
    Description: Athena database containing all Athena tables used by application
    Default: dcdb
    Type: String

  DeliveryBucket:
    Description: bucket which receives output for public distribution
    Type: String
    Default: order-pickup

Conditions:
  ProdEnv: !Equals [!Ref EnvType, prod]

# global tags applied via samconfig.toml profiles
Globals:
  Function:
    Timeout: 3
    Handler: app.lambda_handler
    Runtime: python3.14
    Architectures:
      - x86_64
    Environment:
      Variables:
        LOGLEVEL: WARNING
        # TODO replace most global env variables with function-specific definitions
        ORDERS_TABLE: !Ref OrderTrackingTable
        ATHENA_DATABASE: !Ref AthenaDatabase
        ATHENA_TABLE: !Ref ParquetPartitionedTable
        ATHENA_OUTPUT_BUCKET: !Sub "s3://${DeliveryBucket}/"
        CONFIG_ENVIRONMENT: !Ref EnvType

Resources:
  #
  # resources used by State Machine
  #
  BathymetryStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/bathy_order_processor.asl.json
      Role: !Ref SnfRole
      DefinitionSubstitutions:
        MultibeamCatalogQueueUrl: !Ref MultibeamCatalogQueue
        OrderNotificationQueueUrl: !Ref OrderNotificationQueue
        GridDataQueueUrl: !Ref GridDataQueue
        InsertOrderRecordsFunction: !Ref InsertOrderRecordsFunction
        MultibeamCatalogFunction: !GetAtt MultibeamCatalogFunction.Arn
        NotifyUserFunction: !GetAtt NotifyUserFunction.Arn
        UpdateDatasetRecordFunction: !GetAtt UpdateDatasetRecordFunction.Arn
        UpdateOrderRecordFunction: !GetAtt UpdateOrderRecordFunction.Arn
        FormatPointQueryFunction: !GetAtt FormatPointQueryFunction.Arn
        DatasetErrorHandlerFunction: !GetAtt DatasetErrorHandlerFunction.Arn
        VerifyDatasetStatusFunction: !GetAtt VerifyDatasetStatusFunction.Arn
        AthenaOutputBucket: !Sub "s3://${!Ref DeliveryBucket}/"
        OrderTrackingTable: !Ref OrderTrackingTable

  DatasetErrorHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dataset_error_handler/
      Role: !Ref LambdaRole
      Description: "handle errors in the dataset-specific section of StepFunction"

  FormatPointQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: format_point_query/
      Role: !Ref LambdaRole
      Description: "construct the SQL used by Athena to extract CSB points"
      Environment:
        Variables:
          # TODO standardize variable names
          ATHENA_OUTPUT_BUCKET: !Ref DeliveryBucket
          ATHENA_TABLE: !Ref ParquetPartitionedTable
          ATHENA_DATABASE: !Ref AthenaDatabase

  InsertOrderRecordsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: insert_order_records/
      Role:
        !Ref LambdaRole

  MultibeamCatalogFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: multibeam_catalog_query/
      Role: !Ref LambdaRole
      Description: "queries the ArcGIS mapservice to get a list of multibeam files matching the filter parameters"
      Environment:
        Variables:
          OUTPUT_BUCKET: !Ref DeliveryBucket
          CATALOG_URL: " https://gis.ngdc.noaa.gov/arcgis/rest/services/multibeam_files/MapServer/0/query"

  NotifyUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: notify_user/
      Role: !Ref LambdaRole
      Environment:
        Variables:
          ORDER_NOTIFICATION_QUEUE_URL: !Ref OrderNotificationQueue

  UpdateDatasetRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_dataset_record/
      Role: !Ref LambdaRole
      Environment:
        Variables:
          # TODO standardize variable names
          ORDERS_TABLE: !Ref BathyOrdersTable

  UpdateOrderRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_order_record/
      Role: !Ref LambdaRole
      Environment:
        Variables:
          # TODO standardize variable names
          ORDERS_TABLE: !Ref BathyOrdersTable

  VerifyDatasetStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: verify_dataset_status/
      Role: !Ref LambdaRole
      Environment:
        Variables:
          # TODO standardize variable names
          ORDERS_TABLE: !Ref BathyOrdersTable

  #
  # Functions related to API Gateway
  #
  AutogridApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: !If [ ProdEnv, 'Autogrid API', !Sub '${EnvType} instance of Autogrid API' ]
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - GET
          - POST
          - OPTIONS

  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create_order/
      Role: !Ref LambdaRole
      Description: "validate incoming payload and asynchonously start step function"
      Environment:
        Variables:
          STATE_MACHINE_ARN: !Ref BathymetryStateMachine
      Events:
        bathy:
          Type: HttpApi
          Properties:
            ApiId: !Ref AutogridApi
            Path: /order
            Method: post


  CountPointsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: count_points/
      Role: !Ref LambdaRole
      Description: "count number of points"
      Timeout: 25
#      Environment:
#        Variables:

      Events:
        bathy:
          Type: HttpApi
          Properties:
            ApiId: !Ref AutogridApi
            Path: /count
            Method: get

  ListPlatformsAndProvidersFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: list_platforms/
        Role: !Ref LambdaRole
        Description: "list the platforms and providers"
        Timeout: 25
        Events:
          bathy:
            Type: HttpApi
            Properties:
              ApiId: !Ref AutogridApi
              Path: /platforms
              Method: get

  OrderStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: order_status/
      Role: !Ref LambdaRole
      Description: "report on the status of given order"
      Events:
        csb:
          Type: HttpApi
          Properties:
            ApiId: !Ref AutogridApi
            # TODO use {orderid} instead of {proxy+}?
            Path: /order/{proxy+}
            Method: get

  ListFilesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: list_files/
      Role: !Ref LambdaRole
      Description: "list S3 objects corresponding to given map service query parameters"
      Events:
        csb:
          Type: HttpApi
          Properties:
            ApiId: !Ref AutogridApi
            Path: /files
            Method: get

  #
  # functions related to order processing step function
  #

#  MultibeamCatalogFunction:
#      Type: AWS::Serverless::Function
#      Properties:
#        CodeUri: multibeam_catalog_query/
#        Role: !Ref ExecutionRole
#        Description: "queries the ArcGIS mapservice to get a list of multibeam files matching the filter parameters"
#        Environment:
#          Variables:
#            # TODO replace w/ variable
#            OUTPUT_BUCKET: "csb-pilot-delivery"
#            CATALOG_URL: " https://gis.ngdc.noaa.gov/arcgis/rest/services/multibeam_files/MapServer/0/query"
#        Events:
#          multibeamCatalogQueryEvent:
#            Type: SQS
#            Properties:
#              Queue: !GetAtt MultibeamCatalogQueue.Arn
#              Enabled: true
#
#
#  OrderErrorHandlerFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: order_error_handler/
#      Role: !Ref ExecutionRole
#      Description: "handle errors in the order-specific section of StepFunction"
#
#  OrderSuccessFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: order_success/
#      Role: !Ref ExecutionRole
#      Description: "update database and format notification message when order succeeds"

#  FormatPointQueryFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: format_point_query/
#      Role: !Ref ExecutionRole
#      Description: "construct the SQL used by Athena to extract CSB points"

#  InitializeOrderRecordFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: insert_order_record/
#      Role: !Ref ExecutionRole
#      Description: "insert a new order record into the order tracking table"
#
#  InitializeDatasetRecordFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: insert_dataset_record/
#      Role: !Ref ExecutionRole
#      Description: "insert a new dataset record into the order tracking table"

#  UpdateDatasetRecordFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: update_dataset_record/
#      Role: !Ref ExecutionRole
#      Description: "update the status of the dataset into the order tracking table"

#  VerifyDatasetStatusFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: verify_dataset_status/
#      Role: !Ref ExecutionRole
#      Description: "verify all datasets in order are staged and ready for processing or delivery"

#
# shared resources
#
  SendEmailViaRelayFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: send_email_via_relay/
      Role: !Ref LambdaRole
      Description: "send email message via NCIS email relay"
      Environment:
        Variables:
          #SENDER: "bathydata@iho.int"
          SENDER: "mb.info@noaa.gov"
      VpcConfig:
        SecurityGroupIds:
          - sg-0220bb1b0f1717bd8
        SubnetIds:
          - subnet-00046143f1dcc8109
      Events:
        orderNotificationEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt OrderNotificationQueue.Arn
            Enabled: true

  MultibeamCatalogQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !If [ ProdEnv, 'MultibeamCatalogQueue', !Sub 'MultibeamCatalogQueue-${EnvType}']
      Tags:
        - Key: stack-name
          Value: !Ref AWS::StackName
        - Key: env-type
          Value: !Ref EnvType

  OrderNotificationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !If [ ProdEnv, 'OrderNotificationQueue', !Sub 'OrderNotificationQueue-${EnvType}']
      Tags:
        - Key: stack-name
          Value: !Ref AWS::StackName
        - Key: env-type
          Value: !Ref EnvType

  GridDataQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !If [ ProdEnv, 'GridDataQueue', !Sub 'GridDataQueue-${EnvType}']
      Tags:
        - Key: stack-name
          Value: !Ref AWS::StackName
        - Key: env-type
          Value: !Ref EnvType

#
# DynamoDB Tables
#
  OrderTrackingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !If [ ProdEnv, 'bathy-orders', !Sub 'bathy-orders-${EnvType}']
      Tags:
        - Key: stack-name
          Value: !Ref AWS::StackName
        - Key: env-type
          Value: !Ref EnvType

      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"

      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"

      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "TTL"
        Enabled: True

  StaleGridMessageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
        AlarmName: !If [ ProdEnv, 'csb-stale-grid-message-alarm', !Sub 'csb-state-grid-message-alarm-${EnvType}']
        AlarmDescription: >-
            # Grid Request Alarm
    
            ## generate notification when message(s) remain in queue longer than
            expected
        ActionsEnabled: true
        # TODO create new SNS topic for administrative notifications via email
        # don't use "OKActions" due to "INSUFFICIENT_DATA -> OK" state changes, i.e. empty queue
        AlarmActions:
            - arn:aws:sns:us-east-1:282856304593:csb-email
        InsufficientDataActions: []
        MetricName: ApproximateAgeOfOldestMessage
        Namespace: AWS/SQS
        Statistic: Maximum
        Dimensions:
            - Name: QueueName
              Value: !GetAtt GridDataQueue.QueueName
        Period: 60
        EvaluationPeriods: 1
        DatapointsToAlarm: 1
        Threshold: 300
        ComparisonOperator: GreaterThanThreshold
        TreatMissingData: missing

  #
  # State Machine
  #
#  BathymetryStateMachine2:
#    Type: AWS::Serverless::StateMachine
#    Properties:
#      DefinitionUri: statemachine/bathy_order_processor_v2.asl.json
#      Role: arn:aws:iam::282856304593:role/csb-bathy-sfn-role
#      DefinitionSubstitutions:
#        MultibeamCatalogQueueUrl: !Ref MultibeamCatalogQueue
#        OrderNotificationQueueUrl: !Ref OrderNotificationQueue
#        GridDataQueueUrl: !Ref GridDataQueue
#        MultibeamCatalogFunctionArn: !GetAtt MultibeamCatalogFunction2.Arn
#        UpdateDatasetRecordFunctionArn: !GetAtt UpdateDatasetRecordFunction.Arn
#        InitializeOrderRecordFunctionArn: !GetAtt InitializeOrderRecordFunction.Arn
#        InitializeDatasetRecordFunctionArn: !GetAtt InitializeDatasetRecordFunction.Arn
#        FormatPointQueryFunctionArn: !GetAtt FormatPointQueryFunction.Arn
#        DatasetErrorHandlerFunctionArn: !GetAtt DatasetErrorHandlerFunction.Arn
#        OrderErrorHandlerFunctionArn: !GetAtt OrderErrorHandlerFunction.Arn
#        OrderSuccessFunctionArn: !GetAtt OrderSuccessFunction.Arn
#        #        MultibeamCatalogFunctionArn: !GetAtt MultibeamCatalogFunction.Arn
#        VerifyDatasetStatusFunctionArn: !GetAtt VerifyDatasetStatusFunction.Arn
#        # TODO avoid hardcoded value here with another Parameter?
#        AthenaOutputBucket: "s3://order-pickup/"
#        OrderTrackingTable: !Ref OrderTrackingTable
#  #        OrderTrackingTable: bathy-orders
#
#  BathymetryStateMachine:
#    Type: AWS::Serverless::StateMachine
#    Properties:
#      DefinitionUri: statemachine/bathy_order_processor.asl.json
#      # TODO different role for Step Function than for the Lambdas
##      Role: !Ref ExecutionRole
#      Role: arn:aws:iam::282856304593:role/csb-bathy-sfn-role
#      DefinitionSubstitutions:
#        MultibeamCatalogQueueUrl: !Ref MultibeamCatalogQueue
#        OrderNotificationQueueUrl: !Ref OrderNotificationQueue
#        GridDataQueueUrl: !Ref GridDataQueue
#        UpdateDatasetRecordFunctionArn: !GetAtt UpdateDatasetRecordFunction.Arn
#        InitializeOrderRecordFunctionArn: !GetAtt InitializeOrderRecordFunction.Arn
#        InitializeDatasetRecordFunctionArn: !GetAtt InitializeDatasetRecordFunction.Arn
#        FormatPointQueryFunctionArn: !GetAtt FormatPointQueryFunction.Arn
#        DatasetErrorHandlerFunctionArn: !GetAtt DatasetErrorHandlerFunction.Arn
#        OrderErrorHandlerFunctionArn: !GetAtt OrderErrorHandlerFunction.Arn
#        OrderSuccessFunctionArn: !GetAtt OrderSuccessFunction.Arn
##        MultibeamCatalogFunctionArn: !GetAtt MultibeamCatalogFunction.Arn
#        VerifyDatasetStatusFunctionArn: !GetAtt VerifyDatasetStatusFunction.Arn
#        # TODO avoid hardcoded value here with another Parameter?
#        AthenaOutputBucket: "s3://order-pickup/"
#        OrderTrackingTable: !Ref OrderTrackingTable
##        OrderTrackingTable: bathy-orders


  #
  # Queues
  #

Outputs:
  AutogridApiUrl:
    Description: "API endpoint for orders"
    Value: !Sub "${AutogridApi.ApiEndpoint}/order/"
  EnvType:
    Description: "EnvironmentType"
    Value: !Ref EnvType
  StateMachineArn:
    Description: "Arn for Step Function"
    Value: !Ref BathymetryStateMachine
#  OrderTrackingTable:
#    Value: !Ref OrderTrackingTable
